/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.fs.cloudapp.data;

import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;
import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Definition of ObjectType full_messages.
 *
 * @since 2022-09-09
 */
@PrimaryKeys({"id"})
public final class full_messages extends CloudDBZoneObject implements Serializable {
    private String id;

    @NotNull
    @DefaultValue(stringValue = "test")
    private String text;

    @NotNull
    @DefaultValue(intValue = 0)
    private Integer type;

    @NotNull
    @DefaultValue(stringValue = "test_user")
    private String nickname;

    private String email;

    private String phone_number;

    private String picture_url;

    @NotNull
    @DefaultValue(stringValue = "#ffffff")
    private String color;

    private String credential_provider_id;

    private Date date_ins;

    @NotNull
    @DefaultValue(stringValue = "test_user")
    private String user_id;

    public full_messages() {
        super(full_messages.class);
        this.text = "test";
        this.type = 0;
        this.nickname = "test_user";
        this.color = "#ffffff";
        this.user_id = "test_user";
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getText() {
        return text;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getType() {
        return type;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getNickname() {
        return nickname;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getEmail() {
        return email;
    }

    public void setPhone_number(String phone_number) {
        this.phone_number = phone_number;
    }

    public String getPhone_number() {
        return phone_number;
    }

    public void setPicture_url(String picture_url) {
        this.picture_url = picture_url;
    }

    public String getPicture_url() {
        return picture_url;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public String getColor() {
        return color;
    }

    public void setCredential_provider_id(String credential_provider_id) {
        this.credential_provider_id = credential_provider_id;
    }

    public String getCredential_provider_id() {
        return credential_provider_id;
    }

    public void setDate_ins(Date date_ins) {
        this.date_ins = date_ins;
    }

    public Date getDate_ins() {
        return date_ins;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getUser_id() {
        return user_id;
    }

    public String getFormattedDate() {
        SimpleDateFormat formatter = new SimpleDateFormat("dd.MM.yyyy HH:mm");
        return formatter.format(date_ins);
    }
}
