/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.fs.cloudapp.data;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.EntireEncrypted;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

import java.util.Date;

/**
 * Definition of ObjectType full_message.
 *
 * @since 2022-08-03
 */
@PrimaryKeys({"id"})
public final class full_message extends CloudDBZoneObject {
    private Long id;

    @NotNull
    @DefaultValue(stringValue = "test")
    private String text;

    @NotNull
    @DefaultValue(intValue = 0)
    private Integer type;

    @NotNull
    @DefaultValue(stringValue = "test")
    private String nickname;

    private String email;

    private String phone_number;

    private String picture_url;

    private String color;

    @NotNull
    @DefaultValue(stringValue = "1")
    private String credential_provider_id;

    private Date date_ins;

    public full_message() {
        super(full_message.class);
        this.text = "test";
        this.type = 0;
        this.nickname = "test";
        this.credential_provider_id = "1";
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getText() {
        return text;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getType() {
        return type;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getNickname() {
        return nickname;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getEmail() {
        return email;
    }

    public void setPhone_number(String phone_number) {
        this.phone_number = phone_number;
    }

    public String getPhone_number() {
        return phone_number;
    }

    public void setPicture_url(String picture_url) {
        this.picture_url = picture_url;
    }

    public String getPicture_url() {
        return picture_url;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public String getColor() {
        return color;
    }

    public void setCredential_provider_id(String credential_provider_id) {
        this.credential_provider_id = credential_provider_id;
    }

    public String getCredential_provider_id() {
        return credential_provider_id;
    }

    public void setDate_ins(Date date_ins) {
        this.date_ins = date_ins;
    }

    public Date getDate_ins() {
        return date_ins;
    }

}
