/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.fs.cloudapp.data;

import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;
import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;

import java.util.Date;

/**
 * Definition of ObjectType input_messages.
 *
 * @since 2022-09-09
 */
@PrimaryKeys({"id"})
public final class input_messages extends CloudDBZoneObject {
    private String id;

    @NotNull
    @DefaultValue(stringValue = "test")
    private String text;

    @NotNull
    @DefaultValue(intValue = 0)
    private Integer type;

    @NotNull
    @DefaultValue(stringValue = "test_user")
    private String user_id;

    public input_messages() {
        super(input_messages.class);
        this.text = "test";
        this.type = 0;
        this.user_id = "test_user";
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getText() {
        return text;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getType() {
        return type;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getUser_id() {
        return user_id;
    }

}
