/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.fs.cloudapp.data;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.EntireEncrypted;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

import java.io.Serializable;
import java.util.Date;

/**
 * Definition of ObjectType messages.
 *
 * @since 2022-07-13
 */
@PrimaryKeys({"id"})
public final class messages extends CloudDBZoneObject implements Serializable {
    private Long id;

    @NotNull
    @DefaultValue(stringValue = "testuser")
    private String user_id;

    @NotNull
    @DefaultValue(stringValue = "test")
    private String text;

    @NotNull
    @DefaultValue(intValue = 0)
    private Integer type;

    private Date date;

    public messages() {
        super(messages.class);
        this.user_id = "testuser";
        this.text = "test";
        this.type = 0;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getText() {
        return text;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getType() {
        return type;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public Date getDate() {
        return date;
    }

}
