/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.fs.cloudapp.data;

import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;
import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;

import java.io.Serializable;
import java.util.Date;

/**
 * Definition of ObjectType poll_lunch_choices.
 *
 * @since 2022-09-11
 */
@PrimaryKeys({"id"})
public final class poll_lunch_choices extends CloudDBZoneObject implements Serializable {
    private Integer id;

    @NotNull
    @DefaultValue(stringValue = "Amami")
    private String name;

    public poll_lunch_choices() {
        super(poll_lunch_choices.class);
        this.name = "Amami";
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

}
