/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.fs.cloudapp.data;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.EntireEncrypted;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

import java.io.Serializable;
import java.util.Date;

/**
 * Definition of ObjectType user_messages.
 *
 * @since 2022-07-11
 */
@PrimaryKeys({"id"})
public final class user_messages extends CloudDBZoneObject implements Serializable {
    @NotNull
    @DefaultValue(stringValue = "ciao")
    private String text;

    private String id;

    @NotNull
    @DefaultValue(stringValue = "id")
    private String user_id;

    @NotNull
    @DefaultValue(intValue = 0)
    private Integer type;

    public user_messages() {
        super(user_messages.class);
        this.text = "ciao";
        this.user_id = "id";
        this.type = 0;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getText() {
        return text;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getType() {
        return type;
    }

}
