/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.fs.cloudapp.data;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.EntireEncrypted;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

import java.util.Date;

/**
 * Definition of ObjectType user_push_tokens.
 *
 * @since 2022-06-26
 */
@PrimaryKeys({"token"})
@Indexes({"ind_user:user_id"})
public final class user_push_tokens extends CloudDBZoneObject {
    private String token;

    @NotNull
    @DefaultValue(stringValue = "Fra")
    private String user_id;

    @NotNull
    @DefaultValue(intValue = 0)
    private Integer platform;

    public user_push_tokens() {
        super(user_push_tokens.class);
        this.user_id = "Fra";
        this.platform = 0;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getToken() {
        return token;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setPlatform(Integer platform) {
        this.platform = platform;
    }

    public Integer getPlatform() {
        return platform;
    }

}
